name: patch_me
description: 'Patch Me is an Open Source FREE App that allows parents to track the eye patching time for their children'
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  video_player: ^2.8.1
  appinio_video_player: ^1.2.2
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  random_string: ^2.3.1
  shared_preferences: ^2.2.2
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.8
  cloud_firestore: ^4.14.0
  intl: ^0.18.1
  percent_indicator: ^4.2.3
  firebase_auth: ^4.16.0
  loader_overlay: ^4.0.0
  firebase_analytics: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/patch-me-logo.png
    - assets/videos/patch-me-story.mov

# Launch icon settings
flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/icon/patch-me-icon.png'
  image_path_android: 'assets/icon/patch-me-icon-android.png'
  min_sdk_android: 33 # android min sdk min:16, default 21
  remove_alpha_ios: true

# Splash Screen Settings
flutter_native_splash:
  #general
  color: '#F4F27E'
  image: assets/images/patch-me-logo.png
  android_12:
    image: assets/icon/patch-me-icon-android.png
    icon_background_color: '#F4F27E'
    color: '#F4F27E'
